//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLTK
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class ch_db
    {
        public int id { get; set; }
        public Nullable<int> MaCauHoi { get; set; }
        public Nullable<int> MaDe { get; set; }
		[Display(Name ="Ghi chú")]
        public string GhiChu { get; set; }
		public string SelectedAnswer { get; set; }


		public virtual DeThi DeThi { get; set; }
        public virtual Quiz Quiz { get; set; }
    }
}
