//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLTK
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class DeThi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeThi()
        {
            this.ch_db = new HashSet<ch_db>();
            this.KetQuas = new HashSet<KetQua>();
        }
    
        public int MaDe { get; set; }
		[Display(Name = "Description")]
		public string MoTa { get; set; }
        public Nullable<int> MaMon { get; set; }
		[Display(Name = "Kind")]
		public string LoaiDe { get; set; }
		[Display(Name = "Date Created")]
		public Nullable<System.DateTime> CreateDate { get; set; }
		[Display(Name = "Created by")]
		public Nullable<int> CreateBy { get; set; }
		[Display(Name = "Max Questions")]
		public Nullable<int> MaxQuiz { get; set; }
		[Display(Name = "Status")]
		public Nullable<bool> Status { get; set; }
		[Display(Name = "Duration")]
		public Nullable<int> Time { get; set; }
		[Display(Name = "Audio")]
		public string Audio { get; set; }
		[Display(Name = "Password")]
		public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ch_db> ch_db { get; set; }
        public virtual MonThi MonThi { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KetQua> KetQuas { get; set; }
    }
}
