//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLTK
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class KetQua
    {
        public int MaKetQua { get; set; }
        public Nullable<int> MaThiSinh { get; set; }
		[Display(Name = "Ngày thi")]
		public Nullable<System.DateTime> NgayThi { get; set; }
		[Display(Name = "Điểm")]
		public double Diem { get; set; }
		[Display(Name = "Mã đề")]
		public Nullable<int> MaDe { get; set; }
    
        public virtual ThiSinh ThiSinh { get; set; }
        public virtual DeThi DeThi { get; set; }
    }
}
