//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLTK
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class ThiSinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThiSinh()
        {
            this.KetQuas = new HashSet<KetQua>();
        }
    
        public int MaThiSinh { get; set; }
		[Display(Name = "Họ và tên")]
		public string HoTen { get; set; }
		[Display(Name = "Giới tính")]
		public Nullable<bool> GioiTinh { get; set; }
		[Display(Name = "Ngày sinh")]
		public Nullable<System.DateTime> NgaySinh { get; set; }
		[Display(Name = "Dân tộc")]
		public string DanToc { get; set; }
		[Display(Name = "Address")]
		public string DiaChi { get; set; }
		[Display(Name = "Class")]
		public Nullable<int> MaLop { get; set; }
		[Display(Name = "Niên khóa")]
		public string NienKhoa { get; set; }
		[Display(Name = "Ảnh hồ sơ")]
		public byte[] Image { get; set; }
		[Display(Name = "Mật khẩu")]
		public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KetQua> KetQuas { get; set; }
        public virtual Lop Lop { get; set; }
    }
}
