//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLTK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TracNghiemEntities : DbContext
    {
        public TracNghiemEntities()
            : base("name=TracNghiemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Quyen> Quyens { get; set; }
        public virtual DbSet<MonThi> MonThis { get; set; }
        public virtual DbSet<ch_db> ch_db { get; set; }
        public virtual DbSet<ThiSinh> ThiSinhs { get; set; }
        public virtual DbSet<KetQua> KetQuas { get; set; }
        public virtual DbSet<DeThi> DeThis { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<Quiz> Quizs { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
    }
}
